language: python
python:
  - "2.7"
  - "2.6"
before_install:
  - sh -c set
install: true
before_script: python misc/build_helpers/show-tool-versions.py
script: python setup.py test --reporter=timing
notifications:
  email: true
